"""
Demonstration script: Read and analyze FCF (Future Cost Function) Benders cuts

FCF cuts are generated by NEWAVE/DECOMP hydrothermal optimization models.
They represent the marginal value of water stored in hydro reservoirs,
allowing efficient coordination between long-term (NEWAVE) and short-term (DECOMP)
planning through Benders decomposition.

This script demonstrates:
1. Parsing binary cortdeco.rv2 files
2. Exploring cut structure and fields
3. Extracting water values for hydro plants
4. Filtering active vs inactive cuts
5. Computing cut statistics
"""

using DESSEM2Julia
using Printf

println("="^80)
println("DESSEM2Julia - FCF Cuts Reading Demonstration")
println("="^80)
println()

# Sample data directory
sample_dir = joinpath(@__DIR__, "..", "docs", "Sample", "DS_ONS_102025_RV2D11")
cortdeco_path = joinpath(sample_dir, "cortdeco.rv2")
println("📁 Sample file: $cortdeco_path")
println()

# ============================================================================
# Step 1: Parse binary file
# ============================================================================
println("="^80)
println("Step 1: Parsing Binary FCF Cuts File")
println("="^80)
println()

println("📋 Configuration:")
println("  File: cortdeco.rv2")
println("  Record size: 1664 bytes (NEWAVE/DECOMP standard)")
println("  Mode: Individualized (UHE-based)")
println()

# Typical Brazilian hydro plant codes (major reservoir plants)
# These are common UHE codes used in FCF cut generation
codigos_uhes = [1, 2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

println("💧 Parsing cuts for $(length(codigos_uhes)) hydro plants...")
println()

cuts = parse_cortdeco(
    cortdeco_path,
    tamanho_registro = 1664,
    codigos_uhes = codigos_uhes,
    codigos_submercados = [1, 2, 3, 4],
    ordem_maxima_parp = 12,
    numero_patamares_carga = 3,
)

println("✓ Successfully parsed cortdeco.rv2")
println()
println("📊 Cuts Summary:")
println("  Total cuts loaded:     $(cuts.numero_total_cortes)")
println("  Record size:           $(cuts.tamanho_registro) bytes")
println("  UHE codes configured:  $(length(cuts.codigos_uhes)) plants")
println("  Submarkets:            $(cuts.codigos_submercados)")
println()

# ============================================================================
# Step 2: Explore cut structure
# ============================================================================
println("="^80)
println("Step 2: Exploring Cut Structure")
println("="^80)
println()

println("📝 Understanding FCFCut fields:")
println("  - indice_corte:        Cut sequential number")
println("  - iteracao_construcao: Construction iteration")
println("  - indice_forward:      Forward pass index")
println("  - iteracao_desativacao: Deactivation iteration (0 = active)")
println("  - rhs:                 Independent term (R\\\$)")
println("  - coeficientes:        Cut coefficients (water values, inflows, etc.)")
println()

# Show first 5 cuts
println("🔍 First 5 Cuts:")
println("  " * "─"^76)
println(
    "  $(rpad("Idx", 5)) $(rpad("Iter", 6)) $(rpad("Fwd", 5)) $(rpad("Active", 8)) $(rpad("RHS", 18)) Num Coefs",
)
println("  " * "─"^76)

for (i, cut) in enumerate(cuts.cortes[1:min(5, end)])
    active_str = cut.iteracao_desativacao == 0 ? "Yes" : "No (iter $(cut.iteracao_desativacao))"
    rhs_str = @sprintf("%.2e", cut.rhs)
    println(
        "  $(rpad(cut.indice_corte, 5)) $(rpad(cut.iteracao_construcao, 6)) " *
        "$(rpad(cut.indice_forward, 5)) $(rpad(active_str, 8)) $(rpad(rhs_str, 18)) $(length(cut.coeficientes))",
    )
end
println("  " * "─"^76)
println()

println("📐 Coefficient Structure (individualized mode):")
println("  Position 1-N_uhes:   π_varm_uhe (water value coefficients)")
println("  Position N_uhes+1-:  π_qafl_uhe (inflow coefficients with lags)")
println("  Additional:          GNL thermal coefficients by submarket/pattern")
println()

# ============================================================================
# Step 3: Water value extraction
# ============================================================================
println("="^80)
println("Step 3: Water Value Extraction")
println("="^80)
println()

println("💧 Water values represent the marginal cost of water (R\$/hm³)")
println("   Higher values indicate greater opportunity cost of using water")
println()

# Get water values for several plants
println("🌊 Water Values for Selected Hydro Plants:")
println("  " * "─"^76)
println("  $(rpad("UHE Code", 12)) $(rpad("Water Value", 18)) Interpretation")
println("  " * "─"^76)

# Sample a few plants to show water values
sample_plants = [1, 2, 4, 6, 7, 8, 10]
for uhe_code in sample_plants
    if uhe_code in cuts.codigos_uhes
        wv = get_water_value(cuts, uhe_code)
        interpretation =
            wv > 100 ? "High scarcity value" :
            wv > 50 ? "Moderate value" :
            wv > 10 ? "Normal operation" : "Abundant water"
        wv_str = @sprintf("%.2f R\$/hm³", wv)
        println("  $(rpad(uhe_code, 12)) $(rpad(wv_str, 18)) $interpretation")
    end
end
println("  " * "─"^76)
println()

println("💡 Note: Water values are averaged across all cuts in the file")
println()

# ============================================================================
# Step 4: Active vs inactive cuts
# ============================================================================
println("="^80)
println("Step 4: Active vs Inactive Cuts")
println("="^80)
println()

active_cuts = get_active_cuts(cuts)
inactive_count = length(cuts.cortes) - length(active_cuts)

println("📊 Cut Status Distribution:")
println()
println("  ┌────────────────────────────────────────────┐")
println("  │ Active cuts:   $(rpad(length(active_cuts), 28)) │")
println("  │ Inactive cuts: $(rpad(inactive_count, 28)) │")
println("  └────────────────────────────────────────────┘")
println()

if inactive_count > 0
    println("ℹ️  Inactive cuts explanation:")
    println("   - iteracao_desativacao > 0 indicates cut was replaced")
    println("   - This happens during Benders decomposition iterations")
    println("   - Active cuts are those still valid for the optimization")
    println()

    # Show some inactive cuts
    inactive_cuts = filter(c -> c.iteracao_desativacao > 0, cuts.cortes)
    if !isempty(inactive_cuts)
        println("🗑️  Sample Inactive Cuts (first 3):")
        println("  " * "─"^76)
        println("  $(rpad("Cut Idx", 10)) $(rpad("Deactivated At", 16)) Reason")
        println("  " * "─"^76)
        for cut in inactive_cuts[1:min(3, end)]
            println("  $(rpad(cut.indice_corte, 10)) $(rpad("Iteration $(cut.iteracao_desativacao)", 16)) Replaced by better cut")
        end
        println("  " * "─"^76)
        println()
    end
else
    println("✓ All cuts are currently active (no deactivated cuts)")
    println()
end

# ============================================================================
# Step 5: Statistics
# ============================================================================
println("="^80)
println("Step 5: Cut Statistics")
println("="^80)
println()

stats = get_cut_statistics(cuts)

println("📈 FCF Cuts Statistical Summary:")
println()
println("  ┌────────────────────────────────────────────────────────┐")
println("  │ Category          │ Value                             │")
println("  ├────────────────────────────────────────────────────────┤")
println("  │ Total cuts        │ $(rpad(stats["total_cuts"], 34)) │")
println("  │ Active cuts       │ $(rpad(stats["active_cuts"], 34)) │")
println("  │ Inactive cuts     │ $(rpad(stats["inactive_cuts"], 34)) │")
println("  ├────────────────────────────────────────────────────────┤")
avg_rhs_str = @sprintf("%.2e R\$", stats["avg_rhs"])
min_rhs_str = @sprintf("%.2e R\$", stats["min_rhs"])
max_rhs_str = @sprintf("%.2e R\$", stats["max_rhs"])
println("  │ Average RHS       │ $(rpad(avg_rhs_str, 34)) │")
println("  │ Minimum RHS       │ $(rpad(min_rhs_str, 34)) │")
println("  │ Maximum RHS       │ $(rpad(max_rhs_str, 34)) │")
println("  ├────────────────────────────────────────────────────────┤")
println("  │ Coefficients/cut  │ $(rpad(stats["num_coefficients"], 34)) │")
println("  └────────────────────────────────────────────────────────┘")
println()

# Additional computed statistics
if !isempty(cuts.cortes)
    # Find cuts by construction iteration
    iterations = unique([c.iteracao_construcao for c in cuts.cortes])
    println("🔄 Construction Iterations:")
    println("  Unique iterations: $(length(iterations))")
    println("  Iteration range:   $(minimum(iterations)) to $(maximum(iterations))")
    println()

    # RHS distribution
    all_rhs = [c.rhs for c in cuts.cortes]
    println("💰 RHS Distribution:")
    println("  Mean:   $(@sprintf("%.2e", sum(all_rhs)/length(all_rhs)))")
    println("  Min:    $(@sprintf("%.2e", minimum(all_rhs)))")
    println("  Max:    $(@sprintf("%.2e", maximum(all_rhs)))")
    println()
end

# ============================================================================
# Summary
# ============================================================================
println("="^80)
println("✅ FCF Cuts Demonstration Complete!")
println("="^80)
println()
println("📚 Summary:")
println("  ✓ Parsed binary cortdeco.rv2 file ($(cuts.numero_total_cortes) cuts)")
println("  ✓ Explored cut structure (indices, iterations, RHS, coefficients)")
println("  ✓ Extracted water values for $(length(sample_plants)) hydro plants")
println("  ✓ Analyzed active vs inactive cuts ($(length(active_cuts)) active)")
println("  ✓ Computed statistical summary")
println()
println("🎯 Key Functions Demonstrated:")
println("  - parse_cortdeco()      : Binary file parsing")
println("  - get_water_value()     : Extract marginal water costs")
println("  - get_active_cuts()     : Filter valid cuts")
println("  - get_cut_statistics()  : Summary statistics")
println()
println("📖 Next Steps:")
println("  - Use cut coefficients for decision-making in optimization")
println("  - Combine with other DESSEM data (hydro plants, demands)")
println("  - Analyze cut evolution across iterations")
println()
